backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: "/"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - file: "index.html"
        label: "Startseite (index.html)"
        name: "index"
        extension: "html"
        format: "raw"
        fields:
          - label: "HTML Quellcode"
            name: "body"
            widget: "code"
            default_language: "html"
